version: "3.9"

services:
  maestro-backend:
    build: ./backend
    container_name: maestro_backend
    volumes:
      - /var/lib/orquestra/ops:/var/lib/orquestra/ops
    ports:
      - "3000:3000"
    restart: always

  maestro-frontend:
    build: ./maestro
    container_name: maestro_frontend
    ports:
      - "4200:80"
    depends_on:
      - maestro-backend
    restart: always